[package]
name = "fibo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "fibo1"
path  = "src/fibo1.rs"


[[bin]]
name = "fibo2"
path  = "src/fibo2.rs"

[dependencies]
halo2_proofs = "0.3.0"